#!/usr/bin/expect -f
set timeout 15
spawn ssh -o StrictHostKeyChecking=no xiaog0055@35.200.7.2 "powershell -NoProfile -NonInteractive -Command \"Get-WmiObject -Namespace 'root\\cimv2\\TerminalServices' -Class Win32_TSNetworkAdapterListSetting | ForEach-Object { \\\"\$(\$_.NetworkAdapterLanaID) - \$(\$_.NetworkAdapterName)\\\" }\""
expect {
    "*assword:*" {
        send "&8ayc_/QT^y_XTL\r"
        expect eof
    }
}
